# Generated by Django 2.0.1 on 2018-01-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('userbirth', models.DateField()),
                ('career', models.CharField(max_length=10)),
                ('resident', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
