# Generated by Django 2.0.1 on 2018-01-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('Question1', models.CharField(max_length=20)),
                ('Question2', models.CharField(max_length=20)),
                ('Question3', models.CharField(max_length=20)),
                ('Question4', models.CharField(max_length=20)),
                ('Question5', models.CharField(max_length=20)),
                ('Question6', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'survey_outcome',
            },
        ),
    ]
