# Generated by Django 2.0.1 on 2018-01-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180124_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_outcome',
            name='Question7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='survey_outcome',
            name='Question6',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
