# Generated by Django 2.0.4 on 2018-04-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180124_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('Search_Record', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserRecord',
            },
        ),
    ]
