# Generated by Django 2.0.4 on 2018-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_picsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picsave',
            name='pic',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
