# Generated by Django 2.0.4 on 2018-04-21 15:40

from django.db import migrations, models
import home.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180420_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picsave',
            name='pic',
            field=models.ImageField(max_length=128, storage=home.storage.OverwriteStorage(), upload_to='pic/'),
        ),
    ]
