# Generated by Django 2.0.4 on 2018-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180421_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='Search_Record',
            field=models.CharField(max_length=50),
        ),
    ]
